/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "errorText": { "text": "Default value is \"default.json\" which renders some built in JSON file.", "view": "DC.Text" },
    "errorText1": { "text": "To load an external file use an URL like:", "view": "DC.Text" },
    "errorText2": { "text": "\"file:///Users/David/Desktop/config.json", "view": "DC.Text" },
    "helloText": { "text": "Hello, World!", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "textField": { "view": "DC.TextField" }
};


